### ISSUE TITLE
Incompatible with beta4

### ISSUE THREAD

**Issue by js6pak** [tom-mckinney/upstream-command-line#16]
System.CommandLine beta 4 made `Option` and `Argument` abstract, simplest solution would be to just implement them but unfortunately all `Option`'s constructors are internal now

**Comment by tom-mckinney** [comment]
Sorry I'm just responding to this! This is a great callout. I submitted a [PR](https://github.com/dotnet/command-line-api/pull/1890) and an [issue](https://github.com/dotnet/command-line-api/issues/1889) on the `System.CommandLine` repo. Once that's merged in I'll update this project to support beta4.

**Comment by rcdailey** [comment]
I like the [latest comment](https://github.com/dotnet/command-line-api/issues/1889#issuecomment-1309320386) on the issue you created. Using reflection to create an instance of the generic type might work, right?
